### PGCB Hourly Generation Dataset (Bangladesh)
This dataset, published by the Power Grid Company of Bangladesh (PGCB), provides hourly records of electricity generation, demand, and loadshedding across the national grid.<br>
Source: https://archive.ics.uci.edu/dataset/1175/pgcb+hourly+generation+dataset+(bangladesh)

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

<h3><center>Loading and exploring the DS<h3>

In [2]:
df = pd.read_excel("PGCB_date_power_demand.xlsx")
df.head()

,datetime,generation_mw,demand_mw,load_shedding,gas,liquid_fuel,coal,hydro,solar,wind,india_bheramara_hvdc,india_tripura,india_adani,nepal,remarks
0,2015-04-19 22:00:00,6323.0,6323,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN
1,2015-04-19 21:00:00,6667.0,6667,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN
2,2015-04-19 19:00:00,6897.0,6897,0,4415,1836,161,41,NaN,NaN,444,0,NaN,NaN,NaN
3,2015-04-19 18:30:00,6933.0,6933,0,4423,1862,159,45,NaN,NaN,444,0,NaN,NaN,Evening_Peak
4,2015-04-19 18:00:00,6874.0,6874,0,4319,1892,155,65,NaN,NaN,443,0,NaN,NaN,NaN

In [3]:
df.info()
# The ds shape is 92650 records and 15 columns.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92650 entries, 0 to 92649
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              92650 non-null  datetime64[ns]
 1   generation_mw         92650 non-null  float64
 2   demand_mw             92650 non-null  int64
 3   load_shedding         92650 non-null  int64
 4   gas                   92650 non-null  int64
 5   liquid_fuel           92650 non-null  int64
 6   coal                  92650 non-null  int64
 7   hydro                 92650 non-null  int64
 8   solar                 70517 non-null  float64
 9   wind                  18676 non-null  float64
 10  india_bheramara_hvdc  92650 non-null  int64
 11  india_tripura         92650 non-null  int64
 12  india_adani           7338 non-null   float64
 13  nepal                 5351 non-null   float64
 14  remarks               6393 non-null   object
dtypes: datetime64[ns](1), float64(5), int64(8), object(1)
memory usage: 10.6+ MB

### Finding issues in the DS:

In [4]:
# Let's check the missing value
df.isnull().sum().sort_values(ascending=False)

nepal                   87299
remarks                 86257
india_adani             85312
wind                    73974
solar                   22133
datetime                    0
generation_mw               0
demand_mw                   0
load_shedding               0
gas                         0
liquid_fuel                 0
coal                        0
hydro                       0
india_bheramara_hvdc        0
india_tripura               0
dtype: int64

In [5]:
# let's check, do I have duplicated timestamp values?
df['datetime'].duplicated(keep=False).sum()

813

In [6]:
# duplicate rows
df.duplicated().sum()

160

In [7]:
# let's check the time range of the data. 
print(df['datetime'].min())
print(df['datetime'].max())
# the time range is almost 10 years
# 92650/8760 is around 10.5 years

2015-04-19 00:00:00
2025-06-17 12:00:00

In [8]:
# from first cell that  I noticed that datetime is not sorted.
# Sorting the datetime 
df['datetime'] = pd.to_datetime(df['datetime'])
df = df.sort_values('datetime').reset_index(drop=True)
df.head()

,datetime,generation_mw,demand_mw,load_shedding,gas,liquid_fuel,coal,hydro,solar,wind,india_bheramara_hvdc,india_tripura,india_adani,nepal,remarks
0,2015-04-19 00:00:00,4821.0,4821,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN
1,2015-04-19 01:00:00,3612.0,3612,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN
2,2015-04-19 02:00:00,3727.0,3727,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN
3,2015-04-19 03:00:00,3632.0,3632,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN
4,2015-04-19 04:00:00,3641.0,3641,0,0,0,0,0,NaN,NaN,0,0,NaN,NaN,NaN

In [9]:
df['datetime'].diff().value_counts().head(10)

datetime
0 days 01:00:00    83649
0 days 00:30:00     8336
0 days 00:00:00      432
0 days 02:00:00      178
0 days 03:00:00       11
0 days 01:30:00        8
0 days 10:00:00        4
0 days 11:00:00        4
0 days 07:00:00        4
0 days 12:00:00        4
Name: count, dtype: int64

In [10]:
# The ds has a lot of missing values and duplicated values.
# For wind, india_bheram, india_adani and nepal columns, the missing values are a lot. 
# timestamp has duplicated values
# the time gap between the row is not consistent, data is not recorded at 1 hour interval. 
# the time series is mixed one hour and half hour.

### Handling for each issue in the DS

In [11]:
# Dropping duplicated rows and duplicated timestamps
print(f"Shape of DS before dropping duplicates: {df.shape}")
df = df.drop_duplicates()
df = df[~df['datetime'].duplicated(keep=False)].reset_index(drop=True)
print(f"Shape of DS after dropping duplicates: {df.shape}")

Shape of DS before dropping duplicates: (92650, 15)
Shape of DS after dropping duplicates: (91956, 15)

In [12]:
# Dropping the missing values
# Nepal, remarks, india_adani and wind have a lot of missing values, the best way to handle this is to drop these columns.
df= df.drop(['remarks', 'nepal', 'india_adani', 'wind'], axis=1)

# Making the time series consistent by resampling 
df = df.set_index('datetime').resample('h').mean().reset_index()
# After resampling, I noticed that new missing values are created
# I ckecked the ds and found that exactly 1308 hour that had zero rows
# resampling fills those hours, it creates nan rows for every column, because there is nothing to average.

print("Shape after resampling:", df.shape)
print("\nMissing values after resampling:")
print(df.isnull().sum().sort_values(ascending=False))

Shape after resampling: (89101, 11)

Missing values after resampling:
solar                   21706
generation_mw            1308
demand_mw                1308
load_shedding            1308
gas                      1308
liquid_fuel              1308
coal                     1308
hydro                    1308
india_bheramara_hvdc     1308
india_tripura            1308
datetime                    0
dtype: int64

In [13]:
# let's check the how long consecutive missing hours 
hours_missing = df['generation_mw'].isnull()
hours_missing = hours_missing.groupby((hours_missing != hours_missing.shift()).cumsum()).cumsum()
hours_missing.max()  
# Here is a huge gap, 517 hours

517

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 89101 entries, 0 to 89100
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   datetime              89101 non-null  datetime64[ns]
 1   generation_mw         87793 non-null  float64
 2   demand_mw             87793 non-null  float64
 3   load_shedding         87793 non-null  float64
 4   gas                   87793 non-null  float64
 5   liquid_fuel           87793 non-null  float64
 6   coal                  87793 non-null  float64
 7   hydro                 87793 non-null  float64
 8   solar                 67395 non-null  float64
 9   india_bheramara_hvdc  87793 non-null  float64
 10  india_tripura         87793 non-null  float64
dtypes: datetime64[ns](1), float64(10)
memory usage: 7.5 MB

In [15]:
# To fill the missing hours, I am gonna use interpolate method.
# All my ds columns are numeric, which is good.
# I am gonna set the limit to 24, because I have a huge gap of 517 hours.
# I will have still missing hours. 
df = df.set_index('datetime')
df = df.interpolate(method='time', limit=24)
df = df.reset_index()
df.isnull().sum().sort_values(ascending=False)

solar                   21248
generation_mw             495
demand_mw                 495
load_shedding             495
gas                       495
liquid_fuel               495
coal                      495
hydro                     495
india_bheramara_hvdc      495
india_tripura             495
datetime                    0
dtype: int64

In [ ]:
# I will fix the remaining missing hours by median.
df = df.set_index('datetime')
fill = df.drop(columns='solar').groupby([df.index.hour, df.index.month]).transform('median')
df = df.fillna(fill).reset_index()
df.isnull().sum().sort_values(ascending=False)

solar                   21248
datetime                    0
generation_mw               0
demand_mw                   0
load_shedding               0
gas                         0
liquid_fuel                 0
coal                        0
hydro                       0
india_bheramara_hvdc        0
india_tripura               0
dtype: int64

In [173]:
# Since the solar column has less missing values, I did not drop it like the other columns.
miss_solar = df['solar'].isna()
missing_by_year = (miss_solar.groupby(df['datetime'].dt.year).mean()*100).round(1)
missing_by_hour = (miss_solar.groupby(df['datetime'].dt.hour).mean()*100).round(1)
print("Missing values by year:")
print(missing_by_year)
print("\nMissing values by hour:")
print(missing_by_hour)

Missing values by year:
datetime
2015    100.0
2016    100.0
2017     71.9
2018      0.0
2019      0.0
2020      0.0
2021      0.0
2022      0.0
2023      0.0
2024      0.0
2025      0.0
Name: solar, dtype: float64

Missing values by hour:
datetime
0     23.9
1     23.9
2     23.9
3     23.9
4     23.9
5     23.9
6     23.8
7     23.8
8     23.8
9     23.8
10    23.8
11    23.8
12    23.8
13    23.8
14    23.8
15    23.8
16    23.8
17    23.8
18    23.8
19    23.8
20    23.9
21    23.9
22    23.8
23    23.8
Name: solar, dtype: float64

In [175]:
# 2015 and 2016 have completely missing solar data
# 2017 has around 71% missing solar data
# after 2017, the missing is a lot less.
# I can drop ds before 2018, because of the huge missing values.
df = df[df['datetime'].dt.year >= 2018].reset_index(drop=True)
df.isnull().sum().sort_values(ascending=False)

datetime                0
generation_mw           0
demand_mw               0
load_shedding           0
gas                     0
liquid_fuel             0
coal                    0
hydro                   0
solar                   0
india_bheramara_hvdc    0
india_tripura           0
dtype: int64

In [176]:
df.shape

(65389, 11)

In [177]:
df.head()

,datetime,generation_mw,demand_mw,load_shedding,gas,liquid_fuel,coal,hydro,solar,india_bheramara_hvdc,india_tripura
0,2018-01-01 00:00:00,5183.0,5183.0,0.0,4206.0,330.0,179.0,75.0,0.0,209.0,70.0
1,2018-01-01 01:00:00,4908.0,4908.0,0.0,4134.0,249.0,180.0,75.0,0.0,209.0,64.0
2,2018-01-01 02:00:00,4786.0,4786.0,0.0,4013.0,249.0,177.0,73.0,0.0,209.0,66.0
3,2018-01-01 03:00:00,4599.0,4599.0,0.0,3838.0,231.0,185.0,73.0,0.0,209.0,64.0
4,2018-01-01 04:00:00,4594.0,4594.0,0.0,3878.0,231.0,185.0,73.0,0.0,209.0,64.0

In [16]:
# Now let's check the data distribution of all the columns.
df.describe()

,datetime,generation_mw,demand_mw,load_shedding,gas,liquid_fuel,coal,hydro,solar,india_bheramara_hvdc,india_tripura
count,89101,8.860600e+04,88606.000000,88606.000000,88606.000000,8.860600e+04,88606.000000,88606.000000,67853.000000,88606.000000,88606.000000
mean,2020-05-18 06:00:00,9.416831e+03,8774.821497,82.046399,5119.563380,2.009139e+03,975.427021,96.452075,48.058003,662.580169,93.397287
min,2015-04-19 00:00:00,7.300000e+01,6.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2017-11-02 03:00:00,6.769000e+03,6767.000000,0.000000,4417.000000,6.900000e+02,159.000000,40.000000,0.000000,466.000000,70.000000
50%,2020-05-18 06:00:00,8.362100e+03,8371.000000,0.000000,5023.000000,1.480000e+03,405.000000,78.000000,0.000000,704.000000,96.000000
75%,2022-12-02 09:00:00,1.051200e+04,10590.000000,0.000000,5811.000000,2.405000e+03,1230.000000,149.000000,27.600000,910.000000,126.000000
max,2025-06-17 12:00:00,6.452650e+07,121000.000000,65359.000000,74818.000000,2.922290e+07,31687.000000,5623.000000,2998.000000,76292.000000,1234.000000
std,NaN,2.167587e+05,2728.170254,449.280655,1137.994259,9.824877e+04,1223.774058,71.642512,108.071425,354.046161,46.596907