In [ ]:
# Source of the DS: https://archive.ics.uci.edu/dataset/577/codon+usage
# The target is Kingdom, it classifies organisms into all 11 biological kingdoms.

# LIST OF TASKS:
# Identify original problems again
# Try sampling method
# Try classification synthetic data method: SMOTE / ADASYN / CTGAN
# Try noise management method
# Try overlap management method
# Try outlier management method
# Re analyze the dataset
# Compare original vs optimized
# Evaluate balance and realism

In [2]:
import seaborn as sns
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix
from collections import Counter
from scipy.stats import median_abs_deviation

from imblearn.over_sampling import RandomOverSampler, SMOTENC, ADASYN
from imblearn.under_sampling import RandomUnderSampler, TomekLinks
from sklearn.feature_selection import SelectKBest, mutual_info_classif, f_classif
from sklearn.ensemble import RandomForestClassifier

from sklearn.model_selection import StratifiedKFold, cross_val_score, GridSearchCV
from statsmodels.stats.outliers_influence import variance_inflation_factor
from imblearn.pipeline import Pipeline as ImbPipeline

from sklearn.ensemble import IsolationForest
from sklearn.neighbors import KNeighborsClassifier

<h3><center>Understanding and Exploring the Dataset<h3>

In [3]:
# Loading the ds, using low_memory=False because UUU and UUC have mixed types
df = pd.read_csv('datasets/codon_usage.csv', low_memory=False)
df.head()

,Kingdom,DNAtype,SpeciesID,Ncodons,SpeciesName,UUU,UUC,UUA,UUG,CUU,...,CGG,AGA,AGG,GAU,GAC,GAA,GAG,UAA,UAG,UGA
0,vrl,0,100217,1995,Epizootic haematopoietic necrosis virus,0.01654,0.01203,0.00050,0.00351,0.01203,...,0.00451,0.01303,0.03559,0.01003,0.04612,0.01203,0.04361,0.00251,0.00050,0.00000
1,vrl,0,100220,1474,Bohle iridovirus,0.02714,0.01357,0.00068,0.00678,0.00407,...,0.00136,0.01696,0.03596,0.01221,0.04545,0.01560,0.04410,0.00271,0.00068,0.00000
2,vrl,0,100755,4862,Sweet potato leaf curl virus,0.01974,0.0218,0.01357,0.01543,0.00782,...,0.00596,0.01974,0.02489,0.03126,0.02036,0.02242,0.02468,0.00391,0.00000,0.00144
3,vrl,0,100880,1915,Northern cereal mosaic virus,0.01775,0.02245,0.01619,0.00992,0.01567,...,0.00366,0.01410,0.01671,0.03760,0.01932,0.03029,0.03446,0.00261,0.00157,0.00000
4,vrl,0,100887,22831,Soil-borne cereal mosaic virus,0.02816,0.01371,0.00767,0.03679,0.01380,...,0.00604,0.01494,0.01734,0.04148,0.02483,0.03359,0.03679,0.00000,0.00044,0.00131

In [4]:
df.info()
# that is a huge ds

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13028 entries, 0 to 13027
Data columns (total 69 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Kingdom      13028 non-null  object
 1   DNAtype      13028 non-null  int64
 2   SpeciesID    13028 non-null  int64
 3   Ncodons      13028 non-null  int64
 4   SpeciesName  13028 non-null  object
 5   UUU          13028 non-null  object
 6   UUC          13028 non-null  object
 7   UUA          13028 non-null  float64
 8   UUG          13028 non-null  float64
 9   CUU          13028 non-null  float64
 10  CUC          13028 non-null  float64
 11  CUA          13028 non-null  float64
 12  CUG          13028 non-null  float64
 13  AUU          13028 non-null  float64
 14  AUC          13028 non-null  float64
 15  AUA          13028 non-null  float64
 16  AUG          13028 non-null  float64
 17  GUU          13028 non-null  float64
 18  GUC          13028 non-null  float64
 19  GUA          13028 non-null  float64
 20  GUG          13028 non-null  float64
 21  GCU          13028 non-null  float64
 22  GCC          13028 non-null  float64
 23  GCA          13028 non-null  float64
 24  GCG          13028 non-null  float64
 25  CCU          13028 non-null  float64
 26  CCC          13028 non-null  float64
 27  CCA          13028 non-null  float64
 28  CCG          13028 non-null  float64
 29  UGG          13028 non-null  float64
 30  GGU          13028 non-null  float64
 31  GGC          13028 non-null  float64
 32  GGA          13028 non-null  float64
 33  GGG          13028 non-null  float64
 34  UCU          13028 non-null  float64
 35  UCC          13028 non-null  float64
 36  UCA          13028 non-null  float64
 37  UCG          13028 non-null  float64
 38  AGU          13028 non-null  float64
 39  AGC          13028 non-null  float64
 40  ACU          13028 non-null  float64
 41  ACC          13028 non-null  float64
 42  ACA          13028 non-null  float64
 43  ACG          13028 non-null  float64
 44  UAU          13028 non-null  float64
 45  UAC          13028 non-null  float64
 46  CAA          13028 non-null  float64
 47  CAG          13028 non-null  float64
 48  AAU          13028 non-null  float64
 49  AAC          13028 non-null  float64
 50  UGU          13028 non-null  float64
 51  UGC          13028 non-null  float64
 52  CAU          13028 non-null  float64
 53  CAC          13028 non-null  float64
 54  AAA          13028 non-null  float64
 55  AAG          13028 non-null  float64
 56  CGU          13028 non-null  float64
 57  CGC          13028 non-null  float64
 58  CGA          13028 non-null  float64
 59  CGG          13028 non-null  float64
 60  AGA          13028 non-null  float64
 61  AGG          13028 non-null  float64
 62  GAU          13028 non-null  float64
 63  GAC          13028 non-null  float64
 64  GAA          13028 non-null  float64
 65  GAG          13028 non-null  float64
 66  UAA          13028 non-null  float64
 67  UAG          13028 non-null  float64
 68  UGA          13028 non-null  float64
dtypes: float64(62), int64(3), object(4)
memory usage: 6.9+ MB

In [4]:
# Let's check the duplicated rows
print(f'DS shape:',df.shape)
number_of_duplicated_rows =df.duplicated().sum()
print(f'Number of duplicated rows:{number_of_duplicated_rows}')

DS shape: (13028, 69)
Number of duplicated rows:0

In [5]:
df['UUU']=pd.to_numeric(df['UUU'],errors='coerce')
df['UUC'] = pd.to_numeric(df['UUC'],errors='coerce')

# The DS is big, let's check the unique values in each column.
for column in df.columns:
        print(f"Unique values in {column}: {df[column].unique()}")
# Based on ds description: DNAtype is used to identify the genomic origin of a sequence.

Unique values in Kingdom: ['vrl' 'arc' 'bct' 'phg' 'plm' 'pln' 'inv' 'vrt' 'mam' 'rod' 'pri']
Unique values in DNAtype: [ 0  6  4  2  1  3  7  9  5 11 12]
Unique values in SpeciesID: [100217 100220 100755 ...   9601   9602   9606]
Unique values in Ncodons: [    1995     1474     4862 ...    96254 40662582  8998998]
Unique values in SpeciesName: ['Epizootic haematopoietic necrosis virus' 'Bohle iridovirus'
 'Sweet potato leaf curl virus' ...
 'mitochondrion Pongo pygmaeus pygmaeus' 'Homo sapiens'
 'mitochondrion Homo sapiens']
Unique values in UUU: [0.01654 0.02714 0.01974 ... 0.02314 0.01791 0.00554]
Unique values in UUC: [0.01203 0.01357 0.0218  ... 0.03789 0.03215 0.03555]
Unique values in UUA: [0.0005  0.00068 0.01357 ... 0.03671 0.02285 0.04059]
Unique values in UUG: [0.00351 0.00678 0.01543 ... 0.0004  0.00491 0.00619]
Unique values in CUU: [0.01203 0.00407 0.00782 ... 0.00504 0.0299  0.03415]
Unique values in CUC: [0.03208 0.02849 0.01111 ... 0.04792 0.05322 0.05042]
Unique values in CUA: [0.001   0.00204 0.01028 ... 0.06849 0.06669 0.07604]
Unique values in CUG: [0.0401  0.0441  0.01193 ... 0.04198 0.03973 0.03555]
Unique values in AUU: [0.00551 0.01153 0.02283 ... 0.04923 0.00606 0.02772]
Unique values in AUC: [0.02005 0.0251  0.01604 ... 0.0392  0.06643 0.05137]
Unique values in AUA: [0.00752 0.00882 0.01316 ... 0.0447  0.03677 0.03435]
Unique values in AUG: [0.02506 0.03324 0.0218  ... 0.00718 0.00655 0.00582]
Unique values in GUU: [0.01103 0.00814 0.01625 ... 0.00806 0.0091  0.00629]
Unique values in GUC: [0.0411  0.04071 0.01872 ... 0.01769 0.0023  0.00498]
Unique values in GUA: [0.00902 0.00814 0.01213 ... 0.03062 0.00806 0.03358]
Unique values in GUG: [0.03308 0.03256 0.0107  ... 0.04614 0.03512 0.04154]
Unique values in GCU: [0.01003 0.01085 0.02406 ... 0.00527 0.04286 0.01109]
Unique values in GCC: [0.05013 0.04885 0.01234 ... 0.04682 0.03833 0.03821]
Unique values in GCA: [0.01554 0.01221 0.0144  ... 0.00871 0.00866 0.00576]
Unique values in GCG: [1.103e-02 1.357e-02 5.140e-03 ... 3.000e-05 1.750e-02 1.990e-02]
Unique values in CCU: [0.02356 0.00678 0.01604 ... 0.02842 0.03001 0.02931]
Unique values in CCC: [0.03208 0.02714 0.0146  ... 0.03223 0.04033 0.01979]
Unique values in CCA: [0.01203 0.01221 0.02098 ... 0.03838 0.02328 0.03191]
Unique values in CCG: [5.010e-03 4.070e-03 1.070e-02 ... 1.354e-02 9.000e-05 1.332e-02]
Unique values in UGG: [0.01003 0.01425 0.01728 ... 0.02318 0.01852 0.00433]
Unique values in GGU: [0.01203 0.01221 0.01851 ... 0.00739 0.00655 0.00237]
Unique values in GGC: [0.03158 0.01967 0.00864 ... 0.02873 0.03203 0.02163]
Unique values in GGA: [0.01905 0.02239 0.01172 ... 0.00153 0.0283  0.00503]
Unique values in GGG: [0.02456 0.01289 0.01892 ... 0.02266 0.02287 0.02129]
Unique values in UCU: [0.01353 0.02103 0.01933 ... 0.00536 0.00982 0.00626]
Unique values in UCC: [0.02155 0.01493 0.01419 ... 0.0229  0.02919 0.02995]
Unique values in UCA: [0.00251 0.00407 0.01296 ... 0.02988 0.04265 0.02371]
Unique values in UCG: [6.520e-03 4.750e-03 9.670e-03 ... 8.000e-05 1.148e-02 9.000e-05]
Unique values in AGU: [0.0015  0.00068 0.01337 ... 0.0004  0.02448 0.0209 ]
Unique values in AGC: [0.01554 0.02035 0.01337 ... 0.02825 0.01922 0.01958]
Unique values in ACU: [0.00501 0.0095  0.01851 ... 0.02372 0.02706 0.0328 ]
Unique values in ACC: [0.02105 0.02782 0.01131 ... 0.03481 0.04713 0.05031]
Unique values in ACA: [0.00902 0.01425 0.01419 ... 0.01639 0.03769 0.03446]
Unique values in ACG: [1.053e-02 6.110e-03 1.090e-02 ... 3.000e-05 3.900e-04 1.300e-04]
Unique values in UAU: [0.00501 0.00475 0.02612 ... 0.01765 0.02395 0.00994]
Unique values in UAC: [0.02256 0.02917 0.01275 ... 0.02844 0.03088 0.02223]
Unique values in CAA: [0.00301 0.00407 0.01522 ... 0.01001 0.00502 0.05165]
Unique values in CAG: [0.03108 0.02374 0.02365 ... 0.03748 0.03895 0.03423]
Unique values in AAU: [0.00401 0.00882 0.02962 ... 0.00901 0.01952 0.01351]
Unique values in AAC: [0.02607 0.02917 0.01789 ... 0.03757 0.03326 0.03683]
Unique values in UGU: [0.00251 0.00271 0.01625 ... 0.01596 0.02552 0.01779]
Unique values in UGC: [0.01153 0.01628 0.01234 ... 0.02175 0.01315 0.02461]
Unique values in CAU: [0.00501 0.00204 0.01604 ... 0.00131 0.02211 0.0254 ]
Unique values in CAC: [0.02356 0.01967 0.01687 ... 0.02218 0.0281  0.01802]
Unique values in AAA: [0.01053 0.00543 0.02077 ... 0.01216 0.00831 0.02359]
Unique values in AAG: [0.0386  0.03392 0.03949 ... 0.00728 0.0549  0.04366]
Unique values in CGU: [0.00401 0.00136 0.00864 ... 0.00017 0.00043 0.00039]
Unique values in CGC: [0.00702 0.00678 0.00596 ... 0.01442 0.01044 0.02094]
Unique values in CGA: [0.00401 0.00136 0.00926 ... 0.01843 0.01036 0.01248]
Unique values in CGG: [0.00451 0.00136 0.00596 ... 0.02071 0.02201 0.01037]
Unique values in AGA: [0.01303 0.01696 0.01974 ... 0.0023  0.05124 0.00846]
Unique values in AGG: [0.03559 0.03596 0.02489 ... 0.01681 0.02136 0.01333]
Unique values in GAU: [0.01003 0.01221 0.03126 ... 0.01367 0.00178 0.00451]
Unique values in GAC: [0.04612 0.04545 0.02036 ... 0.02518 0.01901 0.03401]
Unique values in GAA: [0.01203 0.0156  0.02242 ... 0.00873 0.01106 0.00744]
Unique values in GAG: [0.04361 0.0441  0.02468 ... 0.05642 0.00649 0.03689]
Unique values in UAA: [2.510e-03 2.710e-03 3.910e-03 2.610e-03 0.000e+00 1.330e-03 3.300e-04
 1.070e-03 1.380e-03 2.500e-03 2.400e-03 2.330e-03 2.220e-03 2.600e-04
 2.000e-03 2.660e-03 2.320e-03 9.600e-04 7.900e-04 1.400e-03 2.470e-03
 9.400e-04 9.000e-04 6.500e-04 2.800e-04 4.200e-04 1.190e-03 1.350e-03
 1.260e-03 2.900e-04 1.090e-03 8.900e-04 1.110e-03 1.360e-03 4.000e-04
 2.100e-04 4.600e-04 4.500e-04 3.500e-04 1.390e-03 3.400e-04 1.410e-03
 3.700e-04 5.100e-04 6.800e-04 1.643e-02 1.720e-03 1.420e-03 1.540e-03
 1.900e-03 2.020e-03 2.030e-03 2.380e-03 2.070e-03 1.790e-03 2.460e-03
 2.270e-03 1.500e-03 1.370e-03 2.350e-03 1.040e-03 1.550e-03 2.040e-03
 1.730e-03 3.690e-03 9.900e-04 1.490e-03 2.520e-03 1.530e-03 1.300e-03
 1.810e-03 1.960e-03 4.060e-03 1.890e-03 1.590e-03 3.810e-03 2.290e-03
 7.300e-04 1.230e-03 1.470e-03 5.150e-03 1.140e-03 4.100e-04 1.580e-03
 1.700e-03 4.700e-04 1.630e-03 6.070e-03 2.280e-03 3.560e-03 1.750e-03
 3.330e-03 1.710e-03 1.060e-03 2.450e-03 1.680e-03 1.100e-03 6.600e-04
 6.240e-03 2.140e-03 1.600e-03 1.920e-03 1.690e-03 1.910e-03 1.280e-03
 1.020e-03 1.270e-03 8.100e-04 1.560e-03 3.500e-03 1.160e-03 1.760e-03
 5.500e-04 2.670e-03 2.600e-03 2.810e-03 5.600e-04 1.200e-04 1.780e-03
 8.800e-04 6.100e-04 9.700e-04 5.200e-04 9.300e-04 1.440e-03 2.170e-03
 1.310e-03 1.290e-03 1.620e-03 2.680e-03 2.750e-03 3.150e-03 2.100e-03
 1.610e-03 1.900e-04 8.500e-04 9.100e-04 5.700e-04 8.700e-04 3.100e-04
 8.600e-04 7.000e-04 2.910e-03 7.500e-04 8.400e-04 8.300e-04 8.000e-05
 2.000e-05 4.000e-05 1.240e-03 1.320e-03 6.700e-04 1.460e-03 2.340e-03
 5.400e-04 1.150e-03 2.900e-03 1.480e-03 7.700e-04 1.820e-03 1.990e-03
 1.860e-03 1.120e-03 1.180e-03 7.800e-04 2.550e-03 4.800e-04 1.930e-03
 1.300e-04 6.900e-04 5.000e-04 7.100e-04 2.110e-03 3.200e-04 3.000e-04
 9.200e-04 1.740e-03 1.326e-02 2.200e-04 1.450e-03 1.030e-03 1.640e-03
 1.250e-03 1.770e-03 8.000e-04 2.500e-04 5.900e-04 7.000e-05 6.000e-04
 4.450e-03 1.830e-03 3.410e-03 8.200e-04 1.050e-03 1.000e-03 1.500e-04
 1.200e-03 7.600e-04 1.010e-03 4.300e-04 1.430e-03 4.400e-04 3.800e-04
 4.040e-03 1.670e-03 6.400e-04 3.600e-04 1.700e-04 4.150e-03 6.300e-04
 1.600e-04 5.800e-04 6.200e-04 2.820e-03 2.920e-03 3.130e-03 2.262e-02
 1.850e-03 1.080e-03 2.200e-03 2.010e-03 1.660e-03 4.030e-03 4.110e-03
 1.970e-03 2.060e-03 2.440e-03 2.000e-04 8.880e-03 3.600e-03 2.700e-04
 4.900e-04 3.900e-04 7.400e-04 1.870e-03 3.380e-03 2.120e-03 1.800e-04
 3.250e-03 2.730e-03 3.070e-03 1.650e-03 1.800e-03 1.510e-03 3.700e-03
 2.130e-03 3.580e-03 2.560e-03 9.800e-04 1.880e-03 7.200e-04 4.890e-03
 2.620e-03 1.220e-03 3.950e-03 2.370e-03 1.340e-03 2.360e-03 2.700e-03
 3.670e-03 3.170e-03 4.790e-03 2.990e-03 1.980e-03 5.220e-03 2.400e-04
 1.570e-03 2.840e-03 5.300e-04 2.310e-03 2.420e-03 4.050e-03 2.230e-03
 2.150e-03 2.050e-03 1.400e-04 3.620e-03 3.440e-03 2.830e-03 3.940e-03
 2.720e-03 3.990e-03 3.630e-03 3.610e-03 8.370e-03 3.290e-03 2.240e-03
 2.640e-03 2.690e-03 2.740e-03 3.570e-03 3.420e-03 2.970e-03 3.660e-03
 3.590e-03 2.210e-03 2.930e-03 3.530e-03 4.940e-03 5.310e-03 3.190e-03
 3.480e-03 4.240e-03 3.300e-03 3.310e-03 2.950e-03 3.430e-03 3.490e-03
 4.020e-03 2.580e-03 2.650e-03 2.880e-03 2.300e-03 2.410e-03 3.800e-03
 2.960e-03 3.790e-03 3.540e-03 3.640e-03 3.960e-03 2.590e-03 2.770e-03
 3.470e-03 2.800e-03 2.790e-03 4.720e-03 4.420e-03 2.160e-03 4.220e-03
 3.160e-03 1.130e-03 1.210e-03 4.440e-03 3.340e-03 3.260e-03 3.020e-03
 3.030e-03 2.540e-03 3.350e-03 2.780e-03 5.000e-03 4.500e-03 4.910e-03
 4.670e-03 3.210e-03 2.390e-03 2.250e-03 3.450e-03 5.050e-03 5.040e-03
 3.120e-03 1.170e-03 3.270e-03 2.850e-03 3.180e-03 3.720e-03 9.500e-04
 3.760e-03 1.000e-04 1.520e-03 2.570e-03 6.250e-03 4.520e-03 3.820e-03
 3.000e-05 5.000e-05 1.840e-03 2.480e-03 8.410e-03 1.950e-03 3.390e-03
 7.140e-03 3.140e-03 2.630e-03 1.100e-04 3.400e-03 4.000e-03 4.170e-03
 1.940e-03 3.890e-03 3.010e-03 2.300e-04 2.530e-03 3.040e-03 3.510e-03
 9.000e-05 4.560e-03 2.980e-03 2.190e-03 4.530e-03 2.860e-03 5.090e-03
 3.710e-03 3.000e-03 2.760e-03 4.660e-03 2.430e-03 3.900e-03 2.260e-03
 6.080e-03 6.000e-05 4.140e-03 2.090e-03 2.870e-03 4.950e-03 1.105e-02
 3.100e-03 4.080e-03 2.490e-03 4.360e-03 4.390e-03 3.830e-03 3.550e-03
 2.080e-03 5.080e-03 3.360e-03 3.110e-03 3.090e-03 5.030e-03 4.250e-03
 4.460e-03 4.960e-03 4.160e-03 2.890e-03 3.220e-03 8.070e-03 3.230e-03
 3.920e-03 5.430e-03 3.280e-03 4.410e-03 4.730e-03 4.260e-03 2.940e-03
 5.020e-03 3.520e-03 4.870e-03 4.210e-03 5.320e-03 3.200e-03 5.390e-03
 4.270e-03 2.180e-03 4.540e-03 3.060e-03 5.770e-03 3.850e-03 3.780e-03
 5.300e-03 3.840e-03 3.880e-03 5.760e-03 5.140e-03 4.380e-03 1.249e-02
 6.700e-03 4.400e-03 3.240e-03 9.660e-03 3.370e-03 4.300e-03 4.090e-03
 3.080e-03 5.260e-03 5.170e-03 4.840e-03 4.920e-03 4.476e-02 5.130e-03
 4.760e-03 3.050e-03 4.430e-03 3.980e-03 7.600e-03 4.580e-03 1.389e-02
 3.740e-03 4.310e-03 3.930e-03 6.950e-03 3.730e-03 7.020e-03 4.510e-03
 4.550e-03 6.200e-03 4.230e-03 3.860e-03 4.070e-03 4.200e-03 5.800e-03
 3.770e-03 3.750e-03 4.850e-03 5.970e-03 3.460e-03 8.400e-03 4.120e-03
 4.600e-03 4.340e-03 8.580e-03 1.831e-02 7.520e-03 1.029e-02 5.250e-03
 5.180e-03 5.370e-03 1.942e-02 4.320e-03 5.790e-03 6.130e-03 4.980e-03
 4.290e-03 4.930e-03 6.180e-03 7.300e-03 4.280e-03 5.980e-03 1.064e-02
 4.370e-03 2.691e-02 1.752e-02 1.754e-02 5.200e-03 1.923e-02 6.230e-03
 4.350e-03 1.755e-02 5.160e-03 5.640e-03 7.560e-03 5.100e-03 1.237e-02
 2.026e-02 1.634e-02 2.239e-02 1.593e-02 3.650e-03 5.360e-03 6.340e-03
 7.000e-03 1.944e-02 4.100e-03 4.590e-03 4.630e-03 4.190e-03 4.291e-02
 5.570e-03 7.510e-03 8.660e-03 6.110e-03 4.010e-03 5.710e-03 3.680e-03
 5.070e-03 7.750e-03 1.092e-02 1.087e-02 8.490e-03 5.330e-03 6.450e-03
 2.411e-02 3.320e-03 3.484e-02 2.873e-02 4.107e-02 1.467e-02 3.677e-02
 4.520e-02 3.870e-03 2.438e-02 1.500e-02 5.190e-03 4.130e-03 5.900e-03
 4.770e-03 7.670e-03 4.180e-03 5.950e-03 1.145e-02 5.490e-03 4.640e-03
 4.610e-03 6.020e-03 4.680e-03 3.970e-03 5.290e-03 1.875e-02 1.962e-02
 5.740e-03 7.070e-03 7.130e-03 7.100e-03 7.080e-03 7.460e-03 7.690e-03
 5.780e-03 5.350e-03 7.040e-03 6.820e-03 6.590e-03 6.760e-03 7.110e-03
 6.350e-03 6.160e-03 5.440e-03 6.000e-03 5.890e-03 5.730e-03 7.090e-03
 7.120e-03 7.050e-03 6.460e-03 6.390e-03 6.860e-03 4.710e-03 6.150e-03
 4.750e-03 4.810e-03 5.930e-03 5.840e-03 7.060e-03 1.789e-02 1.223e-02
 8.550e-03 4.990e-03 4.830e-03 5.750e-03 1.852e-02 7.240e-03 7.170e-03
 7.180e-03 7.410e-03 6.050e-03 4.480e-03 8.130e-03 7.370e-03 8.320e-03
 9.940e-03 6.720e-03 8.230e-03 8.590e-03 8.570e-03 6.630e-03 7.220e-03
 6.440e-03 7.210e-03 4.690e-03 5.820e-03 6.980e-03 6.890e-03 8.280e-03
 5.520e-03 4.650e-03 5.550e-03 6.670e-03 5.470e-03 1.818e-02 1.010e-02
 6.510e-03 4.740e-03 7.230e-03 6.610e-03 6.560e-03 7.420e-03 6.940e-03
 6.490e-03 7.400e-03 4.700e-03 1.142e-02 8.910e-03 6.420e-03 6.740e-03
 7.190e-03 7.950e-03 5.850e-03 4.490e-03 6.400e-03 5.880e-03 5.460e-03
 1.532e-02 6.310e-03 9.510e-03 9.300e-03 9.220e-03 9.570e-03 5.210e-03
 4.330e-03 6.300e-03 8.020e-03 7.840e-03 8.440e-03 6.680e-03 5.630e-03
 6.800e-03 7.340e-03 6.770e-03 5.590e-03 6.690e-03 4.820e-03 7.880e-03
 7.800e-03 5.920e-03 8.600e-03]
Unique values in UAG: [5.000e-04 6.800e-04 0.000e+00 1.570e-03 4.400e-04 3.800e-04 3.300e-04
 3.600e-04 3.500e-04 7.700e-04 8.700e-04 5.700e-04 5.300e-04 1.030e-03
 7.900e-04 8.000e-04 5.500e-04 9.600e-04 1.220e-03 4.700e-04 3.900e-04
 1.490e-03 8.100e-04 6.500e-04 2.900e-04 2.000e-04 4.600e-04 9.000e-04
 6.000e-05 4.800e-04 1.130e-03 6.100e-04 4.500e-04 4.300e-04 7.100e-04
 4.900e-04 1.100e-04 3.200e-04 8.400e-04 6.300e-04 1.600e-04 4.600e-03
 8.600e-04 4.000e-04 6.400e-04 9.500e-04 5.100e-04 1.530e-03 3.000e-04
 3.100e-04 9.700e-04 8.200e-04 1.400e-04 8.900e-04 7.400e-04 7.500e-04
 7.200e-04 1.100e-03 4.100e-04 3.700e-04 5.900e-04 1.630e-03 8.500e-04
 1.230e-03 1.010e-03 1.520e-03 5.600e-04 1.420e-03 1.320e-03 1.200e-04
 1.200e-03 1.020e-03 2.500e-04 2.040e-03 8.800e-04 1.090e-03 5.400e-04
 1.900e-04 1.120e-03 7.600e-04 2.050e-03 1.830e-03 9.100e-04 9.300e-04
 2.300e-04 6.900e-04 1.340e-03 2.140e-03 1.260e-03 1.150e-03 7.000e-04
 1.700e-04 1.000e-04 6.700e-04 9.200e-04 1.310e-03 1.740e-03 1.040e-03
 2.100e-03 1.800e-04 1.070e-03 1.000e-05 5.000e-05 2.200e-04 1.060e-03
 9.000e-05 2.700e-04 2.400e-04 4.200e-04 5.800e-04 1.080e-03 1.480e-03
 1.660e-03 9.900e-04 1.390e-03 8.300e-04 3.150e-03 1.760e-03 4.770e-03
 2.820e-03 1.140e-03 5.200e-04 2.370e-03 6.600e-04 1.160e-03 2.580e-03
 2.090e-03 2.000e-03 2.440e-03 3.350e-03 1.330e-03 2.520e-03 3.440e-03
 1.790e-03 1.190e-03 1.500e-04 1.240e-03 2.330e-03 2.680e-03 4.000e-05
 1.900e-03 1.820e-03 2.600e-03 2.100e-04 2.800e-04 1.580e-03 1.350e-03
 6.200e-04 2.030e-03 1.460e-03 2.060e-03 1.620e-03 1.730e-03 1.590e-03
 1.540e-03 2.710e-03 5.430e-03 3.460e-03 6.000e-04 2.150e-03 1.280e-03
 2.400e-03 2.010e-03 1.750e-03 2.600e-04 1.300e-03 3.070e-03 1.850e-03
 3.400e-04 1.700e-03 1.990e-03 2.560e-03 1.950e-03 1.910e-03 1.180e-03
 6.500e-03 1.550e-03 1.980e-03 1.770e-03 1.640e-03 9.400e-04 2.890e-03
 1.890e-03 1.380e-03 8.000e-05 4.150e-03 1.500e-03 2.170e-03 3.300e-03
 3.000e-03 6.980e-03 1.170e-03 2.230e-03 1.810e-03 7.800e-04 3.500e-03
 2.360e-03 2.220e-03 1.920e-03 2.290e-03 2.070e-03 2.240e-03 1.360e-03
 1.470e-03 1.800e-03 1.680e-03 9.800e-04 1.250e-03 1.780e-03 2.960e-03
 1.410e-03 1.290e-03 2.210e-03 3.000e-05 3.140e-03 7.000e-05 1.430e-03
 1.560e-03 1.440e-03 2.020e-03 7.300e-04 2.510e-03 2.970e-03 1.210e-03
 1.050e-03 1.710e-03 2.790e-03 1.270e-03 1.300e-04 2.420e-03 3.720e-03
 1.610e-03 1.510e-03 3.570e-03 2.000e-05 2.280e-03 1.000e-03 2.120e-03
 1.600e-03 3.080e-03 4.070e-03 3.960e-03 5.000e-03 1.370e-03 2.470e-03
 2.670e-03 1.670e-03 3.060e-03 1.110e-03 1.400e-03 4.950e-03 1.870e-03
 2.500e-03 1.720e-03 1.650e-03 1.840e-03 2.390e-03 2.310e-03 2.270e-03
 2.380e-03 1.970e-03 2.130e-03 1.450e-03 2.920e-03 2.620e-03 2.300e-03
 2.460e-03 2.660e-03 2.200e-03 1.960e-03 2.190e-03 3.490e-03 3.530e-03
 2.530e-03 2.750e-03 2.320e-03 2.590e-03 1.860e-03 3.550e-03 7.660e-03
 7.350e-03 1.690e-03 2.570e-03 1.880e-03 2.110e-03 2.473e-02 3.130e-03
 3.750e-03 3.420e-03 3.730e-03 2.260e-03 2.430e-03 1.771e-02 2.730e-03
 2.080e-03 7.490e-03 3.370e-03 2.760e-03 3.910e-03 4.390e-03 4.060e-03
 2.561e-02 3.890e-03 3.020e-03 3.410e-03 6.070e-03 1.420e-02 2.410e-03
 3.980e-03 2.630e-03 2.980e-03 1.017e-02 3.650e-03 3.090e-03 7.640e-03
 4.530e-03 1.940e-03 1.930e-03 2.160e-03 6.960e-03 1.142e-02 4.100e-03
 1.250e-02 4.140e-03 4.640e-03 4.940e-03 1.245e-02 2.350e-03 3.470e-03
 3.290e-03 2.340e-03 8.310e-03 1.233e-02 1.046e-02 3.540e-03 6.570e-03
 9.700e-03 2.720e-03 5.780e-03 6.020e-03 4.270e-03 4.280e-03 9.100e-03
 3.270e-03 3.160e-03 1.113e-02 3.630e-03 7.300e-03 4.430e-03 1.262e-02
 5.270e-03 1.101e-02 1.340e-02 9.890e-03 3.260e-03 3.180e-03 2.690e-03
 3.480e-03 2.830e-03 2.650e-03 2.990e-03 2.450e-03 2.490e-03 4.970e-03
 3.880e-03 6.370e-03 7.850e-03 2.870e-03 2.900e-03 1.786e-02 4.230e-03
 2.880e-03 5.960e-03 5.660e-03 3.320e-03 2.930e-03 3.860e-03 2.910e-03
 2.940e-03 2.950e-03 5.700e-03 3.100e-03 2.180e-03 3.520e-03 3.280e-03
 5.850e-03 6.100e-03 6.700e-03 2.250e-03 4.710e-03 3.200e-03 1.029e-02
 5.160e-03 2.850e-03 3.400e-03 3.830e-03 2.540e-03 5.750e-03 3.840e-03
 2.480e-03 2.800e-03 5.320e-03 3.710e-03 3.040e-03 3.990e-03 2.810e-03
 5.290e-03 2.700e-03 3.600e-03 3.120e-03 3.190e-03 5.300e-03 4.040e-03
 8.940e-03 4.090e-03 3.580e-03 3.870e-03 3.170e-03 6.300e-03 4.020e-03
 2.640e-03 3.210e-03]
Unique values in UGA: [0.      0.00144 0.00131 ... 0.01936 0.01901 0.00638]

In [6]:
df  = df.dropna(subset=['UUU', 'UUC'])
# let's check, do I have columns with only one unique value
unique_values = df.columns[df.nunique() == 1]
unique_values

Index([], dtype='object')

In [7]:
df["Kingdom"].value_counts()

Kingdom
bct    2919
vrl    2831
pln    2523
vrt    2077
inv    1345
mam     572
phg     220
rod     215
pri     180
arc     126
plm      18
Name: count, dtype: int64

In [8]:
# Kingdom colum shows biological groups,
# bct = bacteria, vrl = virus
# pln = plant
# inv = invertebrate, mam = mammal 
# To understand better those abbreviations, I used QWEN.

In [10]:
df['DNAtype'].value_counts()

DNAtype
0     9265
1     2899
2      816
4       31
12       5
3        2
9        2
5        2
11       2
6        1
7        1
Name: count, dtype: int64

In [11]:
summary = df.describe().T
summary

,count,mean,std,min,25%,50%,75%,max
DNAtype,13026.0,0.367265,0.688764,0.0,0.00000,0.000000,1.000000,1.200000e+01
SpeciesID,13026.0,130443.036926,124777.067741,7.0,28851.25000,81971.500000,222890.500000,4.653640e+05
Ncodons,13026.0,79617.758483,719755.572570,1000.0,1602.00000,2929.000000,9120.000000,4.066258e+07
UUU,13026.0,0.024818,0.017628,0.0,0.01391,0.021750,0.031308,2.173000e-01
UUC,13026.0,0.023440,0.011598,0.0,0.01538,0.021905,0.029210,9.169000e-02
...,...,...,...,...,...,...,...,...
GAA,13026.0,0.028291,0.014343,0.0,0.01736,0.026085,0.036800,1.448900e-01
GAG,13026.0,0.021683,0.015019,0.0,0.00971,0.020540,0.031128,1.585500e-01
UAA,13026.0,0.001640,0.001785,0.0,0.00056,0.001380,0.002370,4.520000e-02
UAG,13026.0,0.000590,0.000882,0.0,0.00000,0.000420,0.000830,2.561000e-02
UGA,13026.0,0.006179,0.010345,0.0,0.00041,0.001130,0.002890,1.067000e-01

In [9]:
# UAG, UAA, and UGA are very close to zero, when I asked GPT, the response was: 
# These are condon, which instruction for cell to adds one amino acid for building  protein. 
# When it is very low that means, STOP building the chain.

In [10]:
# Having ID number, Species name  and Ncodons are cheat code for model.
df = df.drop(columns=['SpeciesID','SpeciesName', 'Ncodons'])

In [11]:
# let's check can I find any useful information from those columns and kingdom column
stoped_condons = ['UAG', 'UAA', 'UGA']
for column in stoped_condons:
    grouped = df.groupby("Kingdom")[column].quantile([0.5, 0.95, 0.99]).unstack().round(4)
    print(f"\n{column}:")
    display(grouped)
# The gap between 0.5 and 0.95 is very big, but between 0.95 and 0.99 is not that big
# that means there are some outliers in the data, but not many.

UAG:

           0.50    0.95    0.99
Kingdom
arc      0.0006  0.0015  0.0021
bct      0.0005  0.0014  0.0021
inv      0.0005  0.0024  0.0065
mam      0.0003  0.0019  0.0029
phg      0.0002  0.0010  0.0019
plm      0.0006  0.0009  0.0013
pln      0.0004  0.0018  0.0033
pri      0.0003  0.0018  0.0032
rod      0.0000  0.0014  0.0026
vrl      0.0004  0.0018  0.0029
vrt      0.0004  0.0029  0.0043

UAA:

           0.50    0.95    0.99
Kingdom
arc      0.0013  0.0032  0.0038
bct      0.0013  0.0032  0.0046
inv      0.0018  0.0049  0.0190
mam      0.0009  0.0028  0.0034
phg      0.0024  0.0044  0.0050
plm      0.0013  0.0022  0.0030
pln      0.0010  0.0032  0.0049
pri      0.0016  0.0074  0.0087
rod      0.0006  0.0035  0.0093
vrl      0.0009  0.0036  0.0046
vrt      0.0024  0.0070  0.0078

UGA:

           0.50    0.95    0.99
Kingdom
arc      0.0015  0.0028  0.0039
bct      0.0011  0.0034  0.0080
inv      0.0009  0.0257  0.0310
mam      0.0259  0.0316  0.0321
phg      0.0020  0.0034  0.0050
plm      0.0019  0.0027  0.0038
pln      0.0008  0.0028  0.0133
pri      0.0157  0.0282  0.0314
rod      0.0263  0.0316  0.0318
vrl      0.0005  0.0022  0.0035
vrt      0.0242  0.0316  0.0370

<h3><center> Feature Engineering <h3>

### Overlap between classes

In [12]:
# In this step, I am going to check: Are they target' calsses well separated? 
# If I look at the nearest sample in codon space, is it usually from the same kingdom?
# KNN gets training instances and predicts from nearby points
# with neighbors=1,  it uses the single nearest neighbor.

class_encoder = LabelEncoder()
X = df.drop(columns=['Kingdom'])
y = class_encoder.fit_transform(df['Kingdom'])

# DNAtype is catergorica column. 
continuous_columns = [column for column in X.columns if column != 'DNAtype']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
# I am not gonna tune production model here
# I wanna a very local over lap check. 
Overlap_check = KNeighborsClassifier(1, n_jobs=-1).fit(X_train, y_train).predict(X_test)
# Source: https://scikit-learn.org/stable/modules/neighbors.html
print(f" KNN accuracy: {(Overlap_check == y_test).mean():.2f}")

#Making a for loop to check class by class. 
for numeric, name in enumerate(class_encoder.classes_):
    # Which test rows belong to class number? 
    m =y_test == numeric
    acc= (Overlap_check[m]== y_test[m]).mean()
    print(f" {name:4s} (Quantity = {m.sum():4d}): {acc:.3f}" + (" = can be overlapped" if acc < .7 else ""))
# The accuracy is acceptable.
# This Ds is very imbalanced, claases are not equally reliable. 
# KKN says that plm and pri are hard to separate. 
# For debugging in for loop, I used QWEN.

 KNN accuracy: 0.93
 arc  (Quantity =   38): 0.816
 bct  (Quantity =  876): 0.957
 inv  (Quantity =  404): 0.832
 mam  (Quantity =  172): 0.890
 phg  (Quantity =   66): 0.773
 plm  (Quantity =    5): 0.400 = can be overlapped
 pln  (Quantity =  757): 0.959
 pri  (Quantity =   54): 0.630 = can be overlapped
 rod  (Quantity =   64): 0.781
 vrl  (Quantity =  849): 0.966
 vrt  (Quantity =  623): 0.968

d:\ML_DE\Advanced-Data-Analytics-\.venv\lib\site-packages\joblib\externals\loky\backend\context.py:136: UserWarning: Could not find the number of physical cores for the following reason:
found 0 physical cores < 1
Returning the number of logical cores instead. You can silence this warning by setting LOKY_MAX_CPU_COUNT to the number of cores you want to use.
  warnings.warn(
  File "d:\ML_DE\Advanced-Data-Analytics-\.venv\lib\site-packages\joblib\externals\loky\backend\context.py", line 282, in _count_physical_cores
    raise ValueError(f"found {cpu_count_physical} physical cores < 1")

In [13]:
print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of X_test: {X_test.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of X_train: (9118, 65)
Shape of y_train: (9118,)
Shape of X_test: (3908, 65)
Shape of y_test: (3908,)

### Outlier detection and management

In [14]:
# To evaluate, I am gonna build a evaluation function.
# having same model and same test ds for all the evaluations.
# my ds is very imbalanced, so i need a consistent metrics.
def evaluation(X_train, y_train, X_test, y_test, label=""):
    random_forest_model = RandomForestClassifier(n_estimators=300, random_state=42, n_jobs=-1).fit(X_train, y_train)
    predicted = random_forest_model.predict(X_test)
    f1 = f1_score(y_test, predicted, average='macro')
    print(f"{label:25s} F1={f1:.2f}")
    return f1, predicted

baseline_f1, predicted_base = evaluation(X_train, y_train, X_test, y_test, "Baseline")

Baseline                  F1=0.72

In [15]:
# I am going  build two outlier detection methods: IQR + Isolation Forest.
# This methods is recommended by Lecture.

# to not filer out  rare classes.  
train_counts = pd.Series(y_train).value_counts()
small_classes = train_counts[train_counts<60].index

q1, q3 = X_train[continuous_columns].quantile(0.25), X_train[continuous_columns].quantile(0.75)
iqr = q3- q1

# IQR method and Isolation Forest method are used together to detect outliers.
iqr_flag =((X_train[continuous_columns] < q1-1.5*iqr) | (X_train[continuous_columns] > q3 + 1.5 *iqr)).any(axis=1)
iso_flag = IsolationForest(contamination=0.02, random_state=42, n_jobs=-1).fit_predict(X_train[continuous_columns]) == -1
drop_row =iqr_flag & iso_flag &~pd.Series(y_train).isin(small_classes).to_numpy()

X_train_clean = X_train.loc[~drop_row]
y_train_clean = y_train[~drop_row]

print(f"Removed {drop_row.sum()} rows = {drop_row.mean()*100:.1f}%")
outlier_f1, pred_outlier =evaluation(X_train_clean, y_train_clean, X_test, y_test, "After outlier removal")

Removed 183 rows = 2.0%
After outlier removal     F1=0.72

### Noise manangement

In [16]:
# After removing the some suspicious rows in previous cell. 
# do I still improve the model,  if I shrink extreme codon values instead of deleting more rows?
# But in real biological signal, those extreme values can be important, but noise managerment is mentioned in exercise pdf, so I am gonna try it.
# this step can be  useful only if the score clearly improves.

# calculating mad value for each feature.
mad= X_train_clean[continuous_columns].apply(median_abs_deviation)
med = X_train_clean[continuous_columns].median()
X_noise = X_train_clean.copy()
for column in continuous_columns:
    # if mad is zero, the feature does not have useful spread
    if mad[column] > 0:
        X_noise[column] = X_noise[column].clip(max(med[column]-5*mad[column], 0), med[column]+5*mad[column])
f1_noise, predicted_noise = evaluation(X_noise, y_train_clean, X_test, y_test, "After noise clipping")
# Source: https://www.blog.trainindata.com/winsorization-handling-outliers-in-machine-learning/
# F1 score is not improved, I skip this step.

After noise clipping      F1=0.72

### Overlap mangement

In [17]:
# The target is very imbalanced, I am going to use TomekLinks which is under sampling method.
tomelink_method = TomekLinks(sampling_strategy='auto')
X_train_tome, y_train_tome = tomelink_method.fit_resample(X_train_clean, y_train_clean)
print(f"TomekLinks removed {len(y_train_clean)-len(y_train_tome)} boundary samples")
f1_tomek, _ = evaluation(X_train_tome, y_train_tome, X_test, y_test, "After TomekLinks")

TomekLinks removed 38 boundary samples
After TomekLinks          F1=0.73

### Sampling

In [18]:
# Using under sampling and over sampling methods.
# Evlauating both methods with evaluation function which I built before.

# RANDOM OVER SAMPLING:
random_over_sampler = RandomOverSampler(random_state=42)
X_ros, y_ros = random_over_sampler.fit_resample(X_train_clean, y_train_clean)
f1_ros, _ = evaluation(X_ros, y_ros, X_test, y_test, "Random Over Sampling")

# RANDOM UNDER SAMPLING:
random_under_sampler = RandomUnderSampler(random_state=42)
X_rus, y_rus = random_under_sampler.fit_resample(X_train_clean, y_train_clean)
f1_rus, _ = evaluation(X_rus, y_rus, X_test, y_test, "Random Under Sampling")
# I think under sampling threw away valuable data. 
# Over sampling gives more presences to the rare classes, that is why it got better results.

Random Over Sampling      F1=0.77
Random Under Sampling     F1=0.44

### Data Generating

In [19]:
# Generating synthetic minority samples:
# The ADASYN method is not stable for this class structure.

# Controlling the neighborhood used to create new samples.
k_neighbor = min(3, min(Counter(y_train_clean).values())-1)
# smotic can handle catergorical and continues features. 
dna_column = X_train_clean.columns.get_loc("DNAtype")
smotenc = SMOTENC(categorical_features=[dna_column],random_state=42,k_neighbors=k_neighbor)
X_smote, y_smote = smotenc.fit_resample(X_train_clean, y_train_clean)

f1_smote, _ = evaluation(X_smote, y_smote, X_test, y_test, "SMOTE")
# Source: https://imbalanced-learn.org/stable/references/generated/imblearn.over_sampling.SMOTENC.html
# The F1 score shows that balancing the classes acrtually improved the model.

SMOTE                     F1=0.78

In [20]:
# After all optimization steps in this cell, I am gonna check the data properties.

# UCI says:codon frequencies are normalized by total codon count.
# I asked: Google AI mode: What is the valid range for codon columns ?
# The response was:  1. Relative Frequency (0 to 1)
# In a standard frequency matrix where columns sum to 1, the valid range for any individual codon value is [0.0, 1.0]
# Based on that information, the codon columns almost always sum to 1


optimized_df = pd.DataFrame(X_smote, columns=X_train_clean.columns)
# this is a good method to check, Is the generated data still in normalized frequency structure? 
continuous_row_sums = optimized_df[continuous_columns].sum(axis=1)
print(f"Codon row sums mean: {continuous_row_sums.mean():.2f}")
# Class balance:
print(f"\nClass counts after smotenc: {dict(sorted(Counter(y_smote).items()))}")
# What I can see from the output, generated data is in normalized frequency structure.

Codon row sums mean: 1.00

Class counts after smotenc: {0: 1975, 1: 1975, 2: 1975, 3: 1975, 4: 1975, 5: 1975, 6: 1975, 7: 1975, 8: 1975, 9: 1975, 10: 1975}

<h3><center>Comparing original vs optimized<h3>

In [21]:
# After finding out that generating synthetic data is in normalized frequency structure.
# I am gonna seee:  pairwise relationship pattern between original and optimized data.
original_df = X_train.copy()
# Creating correlation matrix for oversampling and original data. 
original_df_correlation = original_df[continuous_columns].corr().to_numpy()
optimized_df_correlation = optimized_df[continuous_columns].corr().to_numpy()
upper = np.triu_indices_from(original_df_correlation, k=1)
# Computing between original and optimized correlation matrices.
# Close to 1 means the same pattern
# Close to 0 weak similarity.
correlation_similarity = np.corrcoef(original_df_correlation[upper], optimized_df_correlation[upper])[0, 1]

print(f"Correlation similarity: {correlation_similarity:.2f}")
# Source: https://stackoverflow.com/questions/73581384/plotting-a-fancy-diagonal-correlation-matrix-with-coefficients-in-upper-triangle
# They are quite similar, which is a good sign.

Correlation similarity: 0.96

In [22]:
# In this cell, I am gonna dive in deeper: 
# testing the pipeline by doing smotenc inside each fold
# Training  on the full resampled training ds and evaluating on X_test, which is untouched ds.
# And then showing which classes are improved?

# Balancing the training fold. 
pipe = ImbPipeline([('SMOTENC', SMOTENC(categorical_features=[dna_column], random_state=42, k_neighbors=k_neighbor)),
                  ('RandomForest', RandomForestClassifier(n_estimators=300, random_state=42, n_jobs=-1))])
# Cross validation
cv_scores = cross_val_score(pipe, X_train_clean, y_train_clean, cv=StratifiedKFold(5, shuffle=True, random_state=42), scoring='f1_macro')
print(f"CV F1 = {cv_scores.mean():.2f}")

CV F1 = 0.79

In [23]:
final_model = RandomForestClassifier(n_estimators=300, random_state=42, n_jobs=-1).fit(X_smote, y_smote)
predicted_final = final_model.predict(X_test)
final_f1 = f1_score(y_test, predicted_final, average="macro")

# baseline comparison
print(f"F1: {final_f1:.2f} VS baseline: {baseline_f1:.2f}")

base_f1 = f1_score(y_test, predicted_base, average=None)
optimized_f1 = f1_score(y_test, predicted_final, average=None)

print(f"\n{'Class':4s} {'Base':>4s} {'Optimized':>8s}")
for name, base, optimized in zip(class_encoder.classes_, base_f1, optimized_f1):
    print(f"{name:4s} {base:6.4f} {optimized:6.4f})") 
# For debugging in for loop, I used QWEN.

F1: 0.78 VS baseline: 0.72

Class Base Optimized
arc  0.5660 0.7324)
bct  0.9393 0.9506)
inv  0.8033 0.8410)
mam  0.8261 0.8537)
phg  0.6186 0.8500)
plm  0.0000 0.0000)
pln  0.9256 0.9399)
pri  0.6824 0.7800)
rod  0.7255 0.7863)
vrl  0.9153 0.9418)
vrt  0.9275 0.9498)

In [ ]:
# The original DS is very imbalanced, that means the model would not learn the rare classes well.
# he baseline Random Forest scored F1=0.72 which is not bad, but that is because of imbalance.
# After removing the outliers and generating synthetic data, the f1 jumped to 78 and CV f1 is 79 which is not overfitting.
# arc jumped from 56 to 73 and phg jumped from 62 to 80. 
# I had a limitation plm is zero for both, that is because smotenc with k=3 neighbors can not  create meaningful synthetic data for plm.

# Is the optimized data realistic?
# Row sums are still average 1, which is expected for codon frequencies.
# Correlation structure similarity = 0.96 which means the relationship between codons did not get damaged.

# What is my limitation? 
# As I mentioned before, plm class is zero for both.
# 78 is not a bad  but not very high 
# map method actually did not help me, that is because continuous features  are already bonded in 0-1 range.